ProjectQLTS/ProjectQLTS/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectQLTS.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ThemSanPham()
        {
            return View();
        }
        public ActionResult SuaSanPham()
        {
            return View();
        }
       
    }
}

ProjectQLTS/ProjectQLTS/Views/SanPham/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!doctype html>
<html>
<head>
    <title></title>
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <h1 style="text-align:center">Sản Phẩm</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Tên sản phẩm</th>
                    <th scope="col">Loại sản phẩm</th>
                    <th scope="col">Giá</th>
                    <th scope="col">Hành động</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Trà sữa chân trâu đen</td>
                    <td>Trà sữa</td>
                    <td>15.000đ</td>
                    <td>
                        <a href="@Url.Action("SuaSanPham","SanPham")">
                            <span class="btn btn-primary">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </span>
                        </a>
                        <a>
                            <span class="btn btn-danger">
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </span>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
        <a href="@Url.Action("ThemSanPham","SanPham")" style="float:right;" class="btn btn-primary ">
            <i class="fa fa-plus" aria-hidden="true"></i>
            Thêm Sản Phẩm
        </a>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Sản Phẩm</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Bạn có chắc chắn không?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary">Xóa</button>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Không</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
</body>
</html>

ProjectQLTS/ProjectQLTS/Views/SanPham/SuaSanPham.cshtml
@{
    ViewBag.Title = "SuaSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!doctype html>
<html>
<head>
    <title></title>
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div>
        <h1 style="text-align:center">Sửa Sản Phẩm</h1>
        <table class="table table-borderless">

            <tbody>
                <tr>
                    <td style="font-size:25px">Ảnh đại diện:</td>
                    <td>
                        <input type="file" value="Chọn tệp" style="font-size:20px" />
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Tên sản phẩm:</td>
                    <td>
                        <input type="text" style="font-size:20px" />
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Loại sản phẩm:</td>
                    <td>
                        <select style="font-size:20px">
                            <option>Trà sữa</option>
                            <option>Trà trái cây</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Giá tiền:</td>
                    <td>
                        <input type="text" style="font-size:20px" />
                    </td>
                </tr>
                <tr>

                    <td>
                        <button style="font-size:25px;float:right">Xác nhận</button>
                    </td>
                    <td>
                        <button style="font-size:25px">Hủy</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

ProjectQLTS/ProjectQLTS/Views/SanPham/ThemSanPham.cshtml
@{
    ViewBag.Title = "ThemSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title></title>
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div>
        <h1 style="text-align:center">Thêm Sản Phẩm</h1>
        <table class="table table-borderless">
           
            <tbody>
                <tr>
                    <td style="font-size:25px">Ảnh đại diện:</td>
                    <td>
                        <input type="file" value="Chọn tệp" style="font-size:20px" />
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Tên sản phẩm:</td>
                    <td>
                        <input type="text" style="font-size:20px" />
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Loại sản phẩm:</td>
                    <td>
                        <select style="font-size:20px">
                            <option>Trà sữa</option>
                            <option>Trà trái cây</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:25px">Giá tiền:</td>
                    <td>
                        <input type="text" style="font-size:20px" />
                    </td>
                </tr>
                <tr>
                    
                    <td>
                        <button style="font-size:25px;float:right">Xác nhận</button>
                    </td>
                    <td>
                        <button style="font-size:25px">Hủy</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>